name: Init the project
on: [push]
jobs:
  buildBootJarWar:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install gradle
      - run: echo "Start building Jar and War ..."
      - run: gradle clean bootBuildImage build war bootJar bootWar
      - run: echo "build ${{ job.status }}"

  bootRun:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: sudo apt install gradle
      - run: echo "Building bootrun !"
      - run: gradle bootRun
      - run: gradle bootTestRun
      - run: echo "Finished."